// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateGroupInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Color       *string `json:"color,omitempty"`
}

type CreateTodoInput struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	GroupID     *string `json:"groupId,omitempty"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateGroupInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Color       *string `json:"color,omitempty"`
}

type UpdateTodoInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Completed   *bool   `json:"completed,omitempty"`
	GroupID     *string `json:"groupId,omitempty"`
}

type UpdateUserAdminInput struct {
	IsAdmin bool `json:"isAdmin"`
}
